1 pool: 
2   vmImage: 'ubuntu-16.04' 
3 trigger: 
4   - master 
5 steps: 
6   - task: CopyFiles@2 
7     displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Templates' 
8     inputs: 
9       SourceFolder: deployment 
10       Contents: '*.json' 
11       TargetFolder: '$(build.artifactstagingdirectory)/Templates' 
12   - task: Npm@1 
13     displayName: 'npm custom' 
14     inputs: 
15       command: custom 
16       verbose: false 
17       customCommand: 'install --production' 
18   - task: ArchiveFiles@2 
19     displayName: 'Archive $(Build.SourcesDirectory)' 
20     inputs: 
21       rootFolderOrFile: '$(Build.SourcesDirectory)' 
22       includeRootFolder: false 
23   - task: PublishBuildArtifacts@1 
24     displayName: 'Publish Artifact: drop' 